/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingappgb;

/**
 *
 * @author gabriel.lsilv15
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        informaçõesPessoais = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        labelSobrenome = new javax.swing.JLabel();
        fieldSobrenome = new javax.swing.JTextField();
        labelIdade = new javax.swing.JLabel();
        fieldIdade = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        fieldSexo = new javax.swing.JComboBox<>();
        labelRG = new javax.swing.JLabel();
        fieldRG = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        fieldCPF = new javax.swing.JTextField();
        Contatos = new javax.swing.JPanel();
        labelTelefoneFixo = new javax.swing.JLabel();
        fieldTelefoneFixo = new javax.swing.JTextField();
        labelCelular = new javax.swing.JLabel();
        fieldCelular = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelPermiteContato = new javax.swing.JLabel();
        radiobuttonSim = new javax.swing.JRadioButton();
        radiobuttonNão = new javax.swing.JRadioButton();
        labelPreferencia = new javax.swing.JLabel();
        checkboxTelefoneFixo = new javax.swing.JCheckBox();
        checkboxCelular = new javax.swing.JCheckBox();
        checkboxEmail = new javax.swing.JCheckBox();
        buttonSair = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        informaçõesPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Pessoais"));

        labelNome.setText("Nome");

        fieldNome.setText("jTextField1");
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        labelSobrenome.setText("Sobrenome");

        fieldSobrenome.setText("jTextField2");

        labelIdade.setText("Idade");

        fieldIdade.setText("jTextField3");

        labelSexo.setText("Sexo");

        fieldSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        fieldSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSexoActionPerformed(evt);
            }
        });

        labelRG.setText("RG");

        fieldRG.setText("jTextField4");
        fieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRGActionPerformed(evt);
            }
        });

        labelCPF.setText("CPF");

        fieldCPF.setText("jTextField5");

        javax.swing.GroupLayout informaçõesPessoaisLayout = new javax.swing.GroupLayout(informaçõesPessoais);
        informaçõesPessoais.setLayout(informaçõesPessoaisLayout);
        informaçõesPessoaisLayout.setHorizontalGroup(
            informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informaçõesPessoaisLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(informaçõesPessoaisLayout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(18, 18, 18)
                        .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelSobrenome))
                    .addGroup(informaçõesPessoaisLayout.createSequentialGroup()
                        .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(informaçõesPessoaisLayout.createSequentialGroup()
                                .addComponent(labelRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informaçõesPessoaisLayout.createSequentialGroup()
                                .addComponent(labelIdade)
                                .addGap(18, 18, 18)
                                .addComponent(fieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCPF, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldCPF)
                    .addComponent(fieldSexo, 0, 100, Short.MAX_VALUE)
                    .addComponent(fieldSobrenome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informaçõesPessoaisLayout.setVerticalGroup(
            informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informaçõesPessoaisLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSobrenome)
                    .addComponent(fieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdade)
                    .addComponent(fieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSexo)
                    .addComponent(fieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRG)
                    .addGroup(informaçõesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCPF)
                        .addComponent(fieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Contatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Contatos"));

        labelTelefoneFixo.setText("Telefone Fixo");

        fieldTelefoneFixo.setText("jTextField6");

        labelCelular.setText("Celular");

        fieldCelular.setText("jTextField7");

        labelEmail.setText("Email");

        fieldEmail.setText("jTextField8");

        labelPermiteContato.setText("Permite Contato");

        radiobuttonSim.setText("Sim");
        radiobuttonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonSimActionPerformed(evt);
            }
        });

        radiobuttonNão.setText("Não");

        labelPreferencia.setText("Preferência");

        checkboxTelefoneFixo.setText("Telefone Fixo");
        checkboxTelefoneFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxTelefoneFixoActionPerformed(evt);
            }
        });

        checkboxCelular.setText("Celular");
        checkboxCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxCelularActionPerformed(evt);
            }
        });

        checkboxEmail.setText("Email");

        javax.swing.GroupLayout ContatosLayout = new javax.swing.GroupLayout(Contatos);
        Contatos.setLayout(ContatosLayout);
        ContatosLayout.setHorizontalGroup(
            ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContatosLayout.createSequentialGroup()
                        .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEmail)
                            .addComponent(labelTelefoneFixo))
                        .addGap(18, 18, 18)
                        .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ContatosLayout.createSequentialGroup()
                                .addComponent(fieldTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(labelCelular)
                                .addGap(18, 18, 18)
                                .addComponent(fieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldEmail)))
                    .addGroup(ContatosLayout.createSequentialGroup()
                        .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ContatosLayout.createSequentialGroup()
                                .addComponent(labelPermiteContato)
                                .addGap(37, 37, 37))
                            .addGroup(ContatosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(radiobuttonSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radiobuttonNão)
                                .addGap(18, 18, 18)))
                        .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContatosLayout.createSequentialGroup()
                                .addComponent(checkboxTelefoneFixo)
                                .addGap(12, 12, 12)
                                .addComponent(checkboxCelular)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxEmail))
                            .addComponent(labelPreferencia))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContatosLayout.setVerticalGroup(
            ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefoneFixo)
                    .addComponent(fieldTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular)
                    .addComponent(fieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPermiteContato)
                    .addComponent(labelPreferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkboxTelefoneFixo)
                        .addComponent(checkboxCelular)
                        .addComponent(checkboxEmail))
                    .addGroup(ContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radiobuttonSim)
                        .addComponent(radiobuttonNão))))
        );

        buttonSair.setText("Sair");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Contatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informaçõesPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addGap(18, 18, 18)
                .addComponent(buttonSalvar)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(informaçõesPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSair)
                    .addComponent(buttonSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Contatos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSexoActionPerformed

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void fieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRGActionPerformed

    private void radiobuttonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttonSimActionPerformed

    private void checkboxTelefoneFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxTelefoneFixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxTelefoneFixoActionPerformed

    private void checkboxCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxCelularActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contatos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSair;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JCheckBox checkboxCelular;
    private javax.swing.JCheckBox checkboxEmail;
    private javax.swing.JCheckBox checkboxTelefoneFixo;
    private javax.swing.JTextField fieldCPF;
    private javax.swing.JTextField fieldCelular;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldIdade;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldRG;
    private javax.swing.JComboBox<String> fieldSexo;
    private javax.swing.JTextField fieldSobrenome;
    private javax.swing.JTextField fieldTelefoneFixo;
    private javax.swing.JPanel informaçõesPessoais;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPermiteContato;
    private javax.swing.JLabel labelPreferencia;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelSobrenome;
    private javax.swing.JLabel labelTelefoneFixo;
    private javax.swing.JRadioButton radiobuttonNão;
    private javax.swing.JRadioButton radiobuttonSim;
    // End of variables declaration//GEN-END:variables
}
